import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.scss';
import SwiperCore, { Pagination, Navigation, Autoplay } from "swiper";
import { Swiper, SwiperSlide } from 'swiper/react';


SwiperCore.use([Pagination, Navigation, Autoplay]);

export default function Home() {
  const banners = [
    { path: '/banner/banner-1.jpeg', link: '/unproduced' },
    { path: '/banner/banner-2.jpeg', link: '/unproduced' },
    { path: '/banner/banner-3.jpeg', link: '/unproduced' },
    { path: '/banner/banner-4.jpeg', link: '/unproduced' },
    { path: '/banner/banner-5.jpeg', link: '/unproduced' },
    { path: '/banner/banner-6.jpeg', link: '/unproduced' },
  ];

  return (
    <Layout>
      <Head>
        <title>酒海市公式ホームページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Swiper
          className={styles.swiper}
          slidesPerView={1}
          pagination={{
            clickable: true,
          }}
          loop
          autoplay
        >
          {banners.map((banner, index: number) => {
            return (
              <SwiperSlide key={index}>
                <Link href={banner.link}>
                  <Image
                    className='not-filer'
                    src={banner.path}
                    layout="responsive"
                    width={600}
                    height={400}
                    alt="banner"
                  />
                </Link>
              </SwiperSlide>
            )
          })}
        </Swiper>

        <div className={styles.life_serch}>
          <div className={styles.life_box}>
            <span>引越し</span>
          </div>
          <div className={styles.life_box}>
            <span>妊娠・出産</span>
          </div>
          <div className={styles.life_box}>
            <span>子育て・教育</span>
          </div>
          <div className={styles.life_box}>
            <span>資源・ごみ</span>
          </div>
          <div className={styles.life_box}>
            <span>税金・保険料</span>
          </div>
          <div className={styles.life_box}>
            <span>介護・福祉</span>
          </div>
          <div className={styles.life_box}>
            <span>防災・防犯</span>
          </div>
          <div className={styles.life_box}>
            <span>就労</span>
          </div>
          <div className={styles.life_box}>
            <span>結婚・離婚</span>
          </div>
          <div className={styles.life_box}>
            <span>葬儀</span></div>
          <div className={styles.life_box}>
            <span>医療・保健</span>
          </div>
          <div className={styles.life_box}>
            <span>渡船・交通</span>
          </div>
        </div>
      </main>
    </Layout>
  )
}
