import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.scss';
import SwiperCore, { Pagination, Navigation, Autoplay } from "swiper";
import { Swiper, SwiperSlide } from 'swiper/react';
import HomeIcon from '@mui/icons-material/Home';
import Pregnantwoman from '@mui/icons-material/PregnantWoman';
import School from '@mui/icons-material/School';
import Delete from '@mui/icons-material/Delete';
import Payments from '@mui/icons-material/Payments';
import Wheelchairpickup from '@mui/icons-material/Wheelchairpickup';
import Flood from '@mui/icons-material/Flood';
import Work from '@mui/icons-material/Work';
import Group from '@mui/icons-material/Group';
import Localhospital from '@mui/icons-material/Localhospital';
import Directionsboat from '@mui/icons-material/Directionsboat';
import Person from '@mui/icons-material/Person';


SwiperCore.use([Pagination, Navigation, Autoplay]);


export default function Home() {
  const [selectTab, setSelectTab] = useState(0);

  const banners = [
    { path: '/banner/banner-1.jpeg', link: '/unproduced' },
    { path: '/banner/banner-2.jpeg', link: '/unproduced' },
    { path: '/banner/banner-3.jpeg', link: '/unproduced' },
    { path: '/banner/banner-4.jpeg', link: '/unproduced' },
    { path: '/banner/banner-5.jpeg', link: '/unproduced' },
    { path: '/banner/banner-6.jpeg', link: '/unproduced' },
  ];

  return (
    <Layout>
      <Head>
        <title>酒海市公式ホームページ</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Swiper
          className={styles.swiper}
          slidesPerView={1}
          pagination={{
            clickable: true,
          }}
          loop
          autoplay
        >
          {banners.map((banner, index: number) => {
            return (
              <SwiperSlide key={index}>
                <Link href={banner.link}>
                  <Image
                    className='not-filer'
                    src={banner.path}
                    layout="responsive"
                    width={600}
                    height={400}
                    alt="banner"
                  />
                </Link>
              </SwiperSlide>
            )
          })}
        </Swiper>

        <div className={styles.life_serch}>
          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <HomeIcon className={styles.life_icon} />
              <span>引越し</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Pregnantwoman className={styles.life_icon} />
              <span>妊娠・出産</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <School className={styles.life_icon} />
              <span>子育て・教育</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Delete className={styles.life_icon} />
              <span>資源・ごみ</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Payments className={styles.life_icon} />
              <span>税金・保険料</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Wheelchairpickup className={styles.life_icon} />
              <span>介護・福祉</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Flood className={styles.life_icon} />
              <span>防災・防犯</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Work className={styles.life_icon} />
              <span>就労</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Group className={styles.life_icon} />
              <span>結婚・離婚</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Person className={styles.life_icon} />
              <span>葬儀</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Localhospital className={styles.life_icon} />
              <span>医療・保健</span>
            </div>
          </Link>

          <Link href='/unproduced'>
            <div className={styles.life_box}>
              <Directionsboat className={styles.life_icon} />
              <span>渡船・交通</span>
            </div>
          </Link>
        </div>

        <div className={styles.news_container}>
          <ul className={styles.tabs}>
            <li
              className={selectTab == 0 ? styles.active : ''}
              onClick={() => setSelectTab(0)}
            >お知らせ</li>
            <li
              className={selectTab == 1 ? styles.active : ''}
              onClick={() => setSelectTab(1)}
            >災害情報</li>
          </ul>

          <div className={styles.contents}>
            <div className={`${styles.news_section} ${selectTab == 0 ? styles.active : ''}`}>
              <ul className={styles.content_list}>
                <li>
                <span className={styles.date}>2022年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2022 開催のお知らせ</a>
                </li>
                <li>
                <span className={styles.date}>2021年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2021 開催のお知らせ</a>
                </li>
                <li>
                <span className={styles.date}>2020年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2020 開催のお知らせ</a>
                </li>
                <li>
                <span className={styles.date}>2019年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2019 開催のお知らせ</a>
                </li>
                <li>
                <span className={styles.date}>2018年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2018 開催のお知らせ</a>
                </li>
                <li>
                <span className={styles.date}>2017年11月21日</span>
                  <a href="/unproduced">酒見市酒浴びフェスティバル 2017 開催のお知らせ</a>
                </li>
              </ul>
            </div>

            <div className={`${styles.news_section} ${selectTab == 1 ? styles.active : ''}`}>
              <ul className={styles.content_list}>
                <li>
                  <span className={styles.date}>2022年11月21日</span>
                  <a href="/unproduced">[地震情報] M1.1 2022年11月21日 1時31分22秒</a>
                </li>
                <li>
                  <span className={styles.date}>2022年11月21日</span>
                  <a href="/unproduced">お知らせ2-1</a>
                </li>
                <li>
                  <span className={styles.date}>2022年11月21日</span>
                  <a href="/unproduced">お知らせ2-1</a>
                </li>
                <li>
                  <span className={styles.date}>2022年11月21日</span>
                  <a href="/unproduced">お知らせ2-1</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </Layout>
  )
}
